<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Appwrite" Version="6.1.0" />
    <PackageReference Include="Avalonia" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.22" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="sqlite-net-pcl" Version="1.11.285" />
  </ItemGroup>
</Project>
