<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net9.0-browser</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WasmBuildNative>true</WasmBuildNative>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    
    <PackageReference Include="Avalonia.Browser" Version="11.3.22" />
    <PackageReference Include="SkiaSharp.NativeAssets.WebAssembly" Version="2.88.9" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.WebAssembly" Version="8.3.1.1" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EducaMais\EducaMais.csproj" />
  </ItemGroup>
</Project>
